# Auto-generated
MARKET_ETF_REQUESTS = {'FHKST121600C0': {'method': 'GET',
                   'query': [{'description': '시장구분코드 (J)',
                              'key': 'FID_COND_MRKT_DIV_CODE',
                              'length': 2,
                              'name': '조건시장분류코드',
                              'required': True,
                              'type': 'string'},
                             {'description': '종목코드',
                              'key': 'FID_INPUT_ISCD',
                              'length': 12,
                              'name': '입력종목코드',
                              'required': True,
                              'type': 'string'},
                             {'description': 'Unique key( 11216 )',
                              'key': 'FID_COND_SCR_DIV_CODE',
                              'length': 5,
                              'name': '조건화면분류코드',
                              'required': True,
                              'type': 'string'}],
                   'title': 'ETF 구성종목시세',
                   'tr_id': 'FHKST121600C0',
                   'url': '/uapi/etfetn/v1/quotations/inquire-component-stock-price'},
 'FHPST02440000': {'method': 'GET',
                   'query': [{'description': 'J',
                              'key': 'FID_COND_MRKT_DIV_CODE',
                              'length': 2,
                              'name': '조건 시장 분류 코드',
                              'required': True,
                              'type': 'string'},
                             {'description': '종목코드',
                              'key': 'FID_INPUT_ISCD',
                              'length': 12,
                              'name': '입력 종목코드',
                              'required': True,
                              'type': 'string'}],
                   'title': 'NAV 비교추이(종목)',
                   'tr_id': 'FHPST02440000',
                   'url': '/uapi/etfetn/v1/quotations/nav-comparison-trend'},
 'FHPST02440100': {'method': 'GET',
                   'query': [{'description': '1분 :60, 3분: 180 … 120분:7200',
                              'key': 'fid_hour_cls_code',
                              'length': 5,
                              'name': 'FID 시간 구분 코드',
                              'required': True,
                              'type': 'string'},
                             {'description': 'E - 고정값',
                              'key': 'fid_cond_mrkt_div_code',
                              'length': 2,
                              'name': 'FID 조건 시장 분류 코드',
                              'required': True,
                              'type': 'string'},
                             {'description': '종목코드',
                              'key': 'fid_input_iscd',
                              'length': 12,
                              'name': 'FID 입력 종목코드',
                              'required': True,
                              'type': 'string'}],
                   'title': 'NAV 비교추이(분)',
                   'tr_id': 'FHPST02440100',
                   'url': '/uapi/etfetn/v1/quotations/nav-comparison-time-trend'},
 'FHPST02440200': {'method': 'GET',
                   'query': [{'description': 'J 입력',
                              'key': 'fid_cond_mrkt_div_code',
                              'length': 2,
                              'name': 'FID 조건 시장 분류 코드',
                              'required': True,
                              'type': 'string'},
                             {'description': '종목코드 (6자리)',
                              'key': 'fid_input_iscd',
                              'length': 12,
                              'name': 'FID 입력 종목코드',
                              'required': True,
                              'type': 'string'},
                             {'description': '조회 시작일자 (ex. 20240101)',
                              'key': 'fid_input_date_1',
                              'length': 10,
                              'name': 'FID 입력 날짜1',
                              'required': True,
                              'type': 'string'},
                             {'description': '조회 종료일자 (ex. 20240220)',
                              'key': 'fid_input_date_2',
                              'length': 10,
                              'name': 'FID 입력 날짜2',
                              'required': True,
                              'type': 'string'}],
                   'title': 'NAV 비교추이(일)',
                   'tr_id': 'FHPST02440200',
                   'url': '/uapi/etfetn/v1/quotations/nav-comparison-daily-trend'}}
