# Auto-generated
MARKET_ETF_RESPONSES = {'FHPST02440000': {'output1': {'fields': [{'description': '',
                                           'key': 'stck_prpr',
                                           'length': 8,
                                           'name': '주식 현재가',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'prdy_vrss',
                                           'length': 8,
                                           'name': '전일 대비',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'prdy_vrss_sign',
                                           'length': 2,
                                           'name': '전일 대비 부호',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'prdy_ctrt',
                                           'length': 4,
                                           'name': '전일 대비율',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'acml_vol',
                                           'length': 12,
                                           'name': '누적 거래량',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'acml_tr_pbmn',
                                           'length': 60,
                                           'name': '누적 거래 대금',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'stck_prdy_clpr',
                                           'length': 10,
                                           'name': '주식 전일 종가',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'stck_oprc',
                                           'length': 10,
                                           'name': '주식 시가2',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'stck_hgpr',
                                           'length': 10,
                                           'name': '주식 최고가',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'stck_lwpr',
                                           'length': 10,
                                           'name': '주식 최저가',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'stck_mxpr',
                                           'length': 10,
                                           'name': '주식 상한가',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'stck_llam',
                                           'length': 10,
                                           'name': '주식 하한가',
                                           'required': True,
                                           'type': 'string'}],
                               'type': 'object'},
                   'output2': {'fields': [{'description': '',
                                           'key': 'nav',
                                           'length': 11,
                                           'name': 'NAV',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'nav_prdy_vrss_sign',
                                           'length': 1,
                                           'name': 'NAV 전일 대비 부호',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'nav_prdy_vrss',
                                           'length': 11,
                                           'name': 'NAV 전일 대비',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'nav_prdy_ctrt',
                                           'length': 8,
                                           'name': 'NAV 전일 대비율',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'prdy_clpr_nav',
                                           'length': 11,
                                           'name': 'NAV전일종가',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'oprc_nav',
                                           'length': 11,
                                           'name': 'NAV시가',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'hprc_nav',
                                           'length': 11,
                                           'name': 'NAV고가',
                                           'required': True,
                                           'type': 'string'},
                                          {'description': '',
                                           'key': 'lprc_nav',
                                           'length': 11,
                                           'name': 'NAV저가',
                                           'required': True,
                                           'type': 'string'}],
                               'type': 'object'}},
 'FHPST02440100': {'output': {'fields': [{'description': '',
                                          'key': 'bsop_hour',
                                          'length': 6,
                                          'name': '영업 시간',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'nav',
                                          'length': 112,
                                          'name': 'NAV',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'nav_prdy_vrss_sign',
                                          'length': 1,
                                          'name': 'NAV 전일 대비 부호',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'nav_prdy_vrss',
                                          'length': 112,
                                          'name': 'NAV 전일 대비',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'nav_prdy_ctrt',
                                          'length': 84,
                                          'name': 'NAV 전일 대비율',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'nav_vrss_prpr',
                                          'length': 112,
                                          'name': 'NAV 대비 현재가',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'dprt',
                                          'length': 82,
                                          'name': '괴리율',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'stck_prpr',
                                          'length': 10,
                                          'name': '주식 현재가',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'prdy_vrss',
                                          'length': 10,
                                          'name': '전일 대비',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'prdy_vrss_sign',
                                          'length': 1,
                                          'name': '전일 대비 부호',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'prdy_ctrt',
                                          'length': 82,
                                          'name': '전일 대비율',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'acml_vol',
                                          'length': 18,
                                          'name': '누적 거래량',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'cntg_vol',
                                          'length': 18,
                                          'name': '체결 거래량',
                                          'required': True,
                                          'type': 'string'}],
                              'type': 'array'}},
 'FHPST02440200': {'output': {'fields': [{'description': '',
                                          'key': 'stck_bsop_date',
                                          'length': 8,
                                          'name': '주식 영업 일자',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'stck_clpr',
                                          'length': 10,
                                          'name': '주식 종가',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'prdy_vrss',
                                          'length': 10,
                                          'name': '전일 대비',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'prdy_vrss_sign',
                                          'length': 1,
                                          'name': '전일 대비 부호',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'prdy_ctrt',
                                          'length': 82,
                                          'name': '전일 대비율',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'acml_vol',
                                          'length': 18,
                                          'name': '누적 거래량',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'cntg_vol',
                                          'length': 18,
                                          'name': '체결 거래량',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'dprt',
                                          'length': 82,
                                          'name': '괴리율',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'nav_vrss_prpr',
                                          'length': 112,
                                          'name': 'NAV 대비 현재가',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'nav',
                                          'length': 112,
                                          'name': 'NAV',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'nav_prdy_vrss_sign',
                                          'length': 1,
                                          'name': 'NAV 전일 대비 부호',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'nav_prdy_vrss',
                                          'length': 112,
                                          'name': 'NAV 전일 대비',
                                          'required': True,
                                          'type': 'string'},
                                         {'description': '',
                                          'key': 'nav_prdy_ctrt',
                                          'length': 84,
                                          'name': 'NAV 전일 대비율',
                                          'required': True,
                                          'type': 'string'}],
                              'type': 'array'}}}
